'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Products
    Public Property Product_ID As Integer
    Public Property Product_Name As String
    Public Property Product_Design As String
    Public Property Product_Color As String
    Public Property Product_Warranty As String
    Public Property CreatedAt As Nullable(Of Date)

End Class
