//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Design { get; set; }
        public string Product_Color { get; set; }
        public string Product_Warranty { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
